plugins {
    id 'java'
    id 'io.qameta.allure' version '2.11.2'
}

group = 'homework'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

allure {
    version = '2.24.0'
    useTestNG {
        version = '2.24.0'
    }
}

dependencies {
    // 1. Основні залежності автоматизації
    implementation 'org.assertj:assertj-core:3.27.7'
    implementation 'org.testng:testng:7.12.0'
    implementation 'com.microsoft.playwright:playwright:1.62.0'
    implementation 'com.github.javafaker:javafaker:1.0.2'

    // 2. Ломбок
    compileOnly 'org.projectlombok:lombok:1.18.46'
    annotationProcessor 'org.projectlombok:lombok:1.18.46'

    // 3. Логування Log4j2
    implementation 'org.slf4j:slf4j-api:2.0.12'
    implementation 'org.apache.logging.log4j:log4j-slf4j2-impl:2.23.1'
    implementation 'org.apache.logging.log4j:log4j-api:2.23.1'
    implementation 'org.apache.logging.log4j:log4j-core:2.23.1'

    // 4. Інтеграція Allure з TestNG
    testImplementation 'io.qameta.allure:allure-testng:2.24.0'
} // ЗАКРИВАЄМО БЛОК DEPENDENCIES САМЕ ТУТ!

// 5. БЛОК TEST ТЕПЕР СТОЇТЬ ОКРЕМO, ЯК І МАЄ БУТИ:
test {
    useTestNG()

    // Примусово вмикаємо UTF-8 кодування для фіксу ієрогліфів (╨Ч╨╜╤Ц...)
    systemProperty "file.encoding", "UTF-8"

    testLogging {
        outputs.upToDateWhen { false }
        showStandardStreams = true
        events "passed", "skipped", "failed"
    }
}
